# Generated by Django 5.1.5 on 2025-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=40, verbose_name='Fullname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('datatime_post', models.DateTimeField(auto_now_add=True, verbose_name='Datatime')),
            ],
        ),
    ]
